[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "browser-use[cli]>=0.5.9",
    "fastapi>=0.116.1",
    "hypercorn>=0.17.3",
    "pydantic-ai[ag-ui,logfire]>=0.7.4",
    "supabase>=2.18.1",
]
